### PR TITLE
Fix icon for open folder

### PR DESCRIPTION
**Pull request by saadq**

### CODE REVIEW

**Comment by leo** [comment]
Thanks for the PR! However, it looks like it's breaking some sub directories on my MBP. Is you 15" MBP retina? Really weird.

screen shot 2016-08-25 at 19 15 42

**Comment by saadq** [comment]
Yeah, it is a retina. Hmm, is your MBP also 15" retina?

**Comment by leo** [comment]
@saadq Yep (Mid 2015) with Sierra on it

**Comment by saadq** [comment]
I'm on El Capitan, but I imagine the OS wouldn't really make a difference? I'm going to close this PR and the issue for now considering this theme has ~20K downloads and no one else has had this issue. I'm quite new to Atom (moved from Sublime) so I'm going to mess around and make sure I didn't mess up any settings or maybe try reinstalling Atom from fresh and then try using your theme. Thanks again for your quick replies.

**Comment by leo** [comment]
No problem! I hope you'll get it fixed 😊

**Pull request closed without merging**
